GET http://localhost:8080/sportEvents
###
GET http://localhost:8080/sportField/2
###
POST http://localhost:8080/sportEvent
Access-Control-Request-Headers:
Content-Type: application/json

{
  "name": "Maksimir",
  "location": "Zagreb"
}
###
PUT http://localhost:8080/sportField/3
Access-Control-Request-Headers:
Content-Type: application/json

{
  "name": "Rujevica",
  "location": "Rijeka"
}
###
DELETE http://localhost:8080/sportField/4